"""add created_by and updated_by on table users

Revision ID: cdec805f1496
Revises: 4c5dc87a45d7
Create Date: 2026-08-23 05:23:33.639662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cdec805f1496"
down_revision: Union[str, Sequence[str], None] = "4c5dc87a45d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.Integer(), nullable=True))

    op.execute("""
        UPDATE users
        SET created_by = id,
            updated_by = id
        """)

    op.alter_column("users", "created_by", nullable=False)
    op.alter_column("users", "updated_by", nullable=False)

    op.create_foreign_key(
        "fk_users_created_by", "users", "users", ["created_by"], ["id"]
    )
    op.create_foreign_key(
        "fk_users_updated_by", "users", "users", ["updated_by"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_updated_by", "users", type_="foreignkey")
    op.drop_constraint("fk_users_created_by", "users", type_="foreignkey")
    op.drop_column("users", "updated_by")
    op.drop_column("users", "created_by")
    # ### end Alembic commands ###
